# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Install Caddy
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
          sudo apt update
          sudo apt install caddy

      - name: Code Coverage
        if: matrix.os == 'ubuntu-latest'
        run: npm run ci

      - name: Code Coverage without shell test
        if: matrix.os != 'ubuntu-latest'
        run: npm run ci-without-shell

      - name: Upload Coverage Report To Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
